#!/usr/bin/env bash
#Script that installs nginx and configures it on a remote server
#Update packages
sudo apt-get -y update
# Install nginx
sudo apt-get -y install nginx
#Return a HTML page with string Hello World
echo "Hello World!" | sudo tee /var/www/html/index.html
#Restart nginx
sudo service nginx restart
