#!/usr/bin/env bash
# Configure Nginx server so that it is redirecting to another page.
# But the main domain still shows Hello world

sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Redirect the page 301 moved permanently
sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default
service nginx restart
