#!/usr/bin/env bash
# Configure Nginx server to give error 404 page
# Update package lists and install Nginx
sudo apt-get -y update

# install Nginx
sudo apt-get -y install nginx

# Create or edit content in this dir
sudo chown -R "$USER":"$USER" /var/www

# Create an index.html file containing Hello World!
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Set default port to 80 and redirect to this link
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Create this dir
sudo mkdir -p /var/www/error

# Echo this text
echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html

# Return 404
sudo sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/;internal; }' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
